### ISSUE TITLE
Release Management

### ISSUE THREAD

**Issue by hilakista** [ob-vss-ss18/ppl-customer#18]
* Branch `release`
* Pre-Release 1 auf diesen commiten und mit `pre-release-1` taggen
* Auf Heroku deployen
* Heroku `dev` serive einrichten

Siehe [Release Management](https://github.com/ob-vss-ss18/ppl-core/wiki/Release-Management)

**Comment by LukasMarckmiller** [comment]
https://github.com/ob-vss-ss18/ppl-customer/releases

Heroku Address: https://ppl-customer.herokuapp.com/
