### ISSUE TITLE
MongoDB Integration

### ISSUE THREAD

**Issue by LukasMarckmiller** [ob-vss-ss18/ppl-customer#3]

**Comment by LukasMarckmiller** [comment]
**Umstellung auf PostgreSQL ?**

**Comment by HmSebastianH** [comment]
@LukasMarckmiller Würd ich n neues ticket für machen und mir am Montag mal anschauen 😃

**Comment by LukasMarckmiller** [comment]
Neuer Issue ist angelegt.
Ich würde diesen offen lassen bis die neue Lösung vollständig implementiert ist.
