### ISSUE TITLE
Continuous Integration 

### ISSUE THREAD

**Issue by LukasMarckmiller** [ob-vss-ss18/ppl-customer#7]
**mit z.B. Travis-CI, Jenkins, Coverage.io,...**

**Comment by LukasMarckmiller** [comment]
-> https://github.com/ob-vss-ss18/ppl-customer/settings/installations

**Comment by Faaux** [comment]
Tag Commits: 
7c2542e4acc916cb8e33a24ae7296d77e59bbcc3
a67330489d530ad1464aeea2c057337bcd33dabc
